#!/bin/bash

# setup a working directory for c++ development, including support for vscode

# usage csetup.bash name
#   use -v to not configure for vscode

# improve by using a function
#   and using a regex for no dotfiles
if [ $# -eq 1 ]; then

    cp $HOME/.cppsetup/* $1
    if [ $? -eq 0 ]; then
        echo "cppsetup success"
    fi

    cp $HOME/.cppsetup/.* $1
    if [ $? -eq 0 ]; then
        echo "cppsetup vscode is configured"
    fi

elif [ $# -eq 2 ]; then
    if [ $1 == "-v" ]; then
        cp $HOME/.cppsetup/src/ $2
        cp $HOME/.cppsetup/headers/ $2

        if [ $? -eq 0 ]; then
            echo "cppsetup success"
            echo "cppsetup vscode not configured"
            fi
    else
        echo "Incorrect arguments"
    fi
else 
    echo "Incorrect arguments"
fi